version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: restaurant_web
    ports:
      - "8081:80"
    environment:
      DB_HOST: db
      DB_USER: appuser
      DB_PASS: apppass
      DB_NAME: restaurant_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: restaurant_db
    restart: always
    environment:
      MYSQL_DATABASE: restaurant_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/restaurants.sql:/docker-entrypoint-initdb.d/restaurants.sql

volumes:
  db_data:
